In [2]:
import numpy as np

In [6]:
# abc = np.array(['a','b'])

In [8]:
# print(abc)

['a' 'b']


In [10]:
# arr1=np.array([10,20,30,40])
# print(arr1/2)

[ 5. 10. 15. 20.]


In [13]:
# arr1=np.array([10,20,30,40])
# arr2= np.array([1,2,3,4])
# print(arr1&arr2)
# print(arr1|arr2)
# print(arr1^arr2)
# print(arr1<<arr2)
# print(arr1>>arr2)

[0 0 2 0]
[11 22 31 44]
[11 22 29 44]
[ 20  80 240 640]
[5 5 3 2]


In [25]:
# arr3=np.array([[[10,20,30,40],[50,60,70,80]],[[90,91,92,93],[94,95,96,97]]])


[[95]
 [91]]


In [26]:
# print(arr3[1,::-1,1:2:])

[[95]
 [91]]


In [ ]:
# n=int(input("n: "))


In [5]:
import numpy as np
a1=np.array([[10,20],[30,40]])
a2=np.reshape(a1, shape=[1,4])
print(a1)
print(a2)

[[10 20]
 [30 40]]
[[10 20 30 40]]


In [6]:
a1=np.array([[10,20,1],[30,40,2],[50,60,3],[70,80,4]])
a2=np.reshape(a1, shape=[6,2])
print(a1)
print(a2)

[[10 20  1]
 [30 40  2]
 [50 60  3]
 [70 80  4]]
[[10 20]
 [ 1 30]
 [40  2]
 [50 60]
 [ 3 70]
 [80  4]]


In [8]:
a1=np.array([8,2,1,3,9])
b=np.median(a1)
print(b)
print(a1)

3.0
[8 2 1 3 9]


In [7]:
a1=np.array([8,2,1,3,9])
b=np.median(a1,overwrite_input=True)
print(b)
print(a1)

3.0
[1 2 3 8 9]


In [1]:
a1=np.array([8,9,7,5,6,1,2,3,4,10])
b=np.percentile(a1,23,overwrite_input=True)
print(a1)
print(b)

NameError: name 'np' is not defined

In [14]:
a1=np.arange(1,6)
a2=np.cumprod(a1)
print(a2)

[  1   2   6  24 120]
